services:
  web:
    image: openjdk:17-jdk-slim
    ports:
      - "8080:80"
    volumes:
      - ./:/app
    working_dir: /app
    command: "./gradlew bootRun"
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
